name: "Build and push"
on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Docker build and push
    if: >
      ${{ !github.event.deleted &&
      github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: '0'
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
